name: Pelican Builder

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.3
    - uses: astral-sh/setup-uv@v1
      with:
        version: "latest"
    - name: Install dependencies
      run: uv sync -p 3.13
    - name: Build the prod site
      run: |
        source .venv/bin/activate
        make publish
    - name: Add nojekyll
      run: |
        touch ./output/.nojekyll

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: output-website
      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./output/
      - uses: actions/deploy-pages@v4